spring.application.name=Digital Hub Pro
spring.data.mongodb.uri=mongodb+srv://mryuki269_db_user:yuki269@cluster0.nh151wl.mongodb.net/Hub?retryWrites=true&w=majority&authSource=admin
server.port=8081
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
#debug=true